development:
  google_client_id: 697688629201-44s2eiesfem8qp13elra463rrciv6p1a
  google_secret_key: WWRiHnvUuDjgIy374I1e8Hyz

production:
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret_key: <%= ENV["GOOGLE_SECRET_KEY"] %>
