development:
  google_client_id: 697688629201-44s2eiesfem8qp13elra463rrciv6p1a
  google_client_secret: WWRiHnvUuDjgIy374I1e8Hyz

production:
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_SECRET_KEY"] %>
